project:
  type: book
  render:
    - "*.qmd"
    - "!xl*.qmd"
    - "!geographic-basics.qmd"
    - "!geographicanalysis.qmd"
    - "!textanalysis.qmd"
    - "!prep.qmd"
    - "!labs/"
    - "!pre_labs/"
    - "!data/"
    - "!images/"
    - "!automating_analysis.qmd"
    - "!gss.qmd"
    - "!reverse_engineering*"

book:
  title: "Data Journalism with R and the Tidyverse"
  subtitle: "JOUR 472/772, Religion Edition"
  author: "Derek Willis"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - start-story.qmd
    - start-math.qmd
    - start-data-def.qmd
    - ethics.qmd
    - publicrecords.qmd
    - github.qmd
    - r-basics.qmd
    - replication.qmd
    - aggregates.qmd
    - filters.qmd
    - workingwithdates.qmd
    - mutating.qmd
    - data-cleaning-part-i.qmd
    - data-cleaning-part-ii.qmd
    - open-refine.qmd
    - pdfs.qmd
    - merging.qmd
    - census.qmd
    - visualizing-for-reporting.qmd
    - visualizing-for-publication.qmd
    - rvest.qmd
    - basicstats.qmd
    - ai_and_llms.qmd
    - writingwithdata.qmd

format:
  html:
    theme: simplex

editor: visual
